import { z } from 'zod'

export const registerSchema = z.object({
  username: z.string().min(3).max(50),
  email: z.string().email(),
  password: z.string().min(8).max(100),
  phone: z.string().optional(),
  profilePhoto: z.string().url().optional(),
})

export const buyerRegisterSchema = z.object({
  name: z.string().min(2).max(50),
  email: z.string().email(),
  phone: z.string().min(6).max(30),
  password: z.string().min(8).max(100),
  profilePhoto: z.string().url().optional(),
})

export const loginSchema = z.object({
  email: z.string().email(),
  password: z.string().min(1),
})

export const propertySchema = z.object({
  title: z.string().min(1).max(200),
  type: z.string().min(1),
  listingType: z.enum(['For Sale', 'For Rent']),
  price: z.number().positive(),
  priceType: z.string(),
  region: z.string().min(1),
  city: z.string().min(1),
  subCity: z.string().optional(),
  woreda: z.string().optional(),
  kebele: z.string().optional(),
  parcel: z.string().optional(),
  block: z.string().optional(),
  homeNo: z.string().optional(),
  area: z.number().positive().optional(),
  bedrooms: z.number().int().min(0).optional(),
  bathrooms: z.number().int().min(0).optional(),
  condition: z.string().optional(),
  legalizedYear: z.number().int().min(1900).max(2030).optional(),
  description: z.string().optional(),
  features: z.array(z.string()).optional(),
  images: z.array(z.string()).optional(),
  videoUrl: z.string().optional(),
  featured: z.boolean().optional(),
  latitude: z.number().optional(),
  longitude: z.number().optional(),
  name: z.string().optional(),
  phone: z.string().optional(),
  locationDocument: z.string().optional(),
  posterType: z.string().optional(),
  ownerType: z.string().optional(),
})

export const vehicleSchema = z.object({
  title: z.string().min(1).max(200),
  vehicleId: z.string().min(1),
  listingType: z.enum(['For Sale', 'For Rent', 'Both']),
  vehicleCategory: z.string().min(1),
  make: z.string().min(1),
  vehicleModel: z.string().min(1),
  trimVersion: z.string().optional(),
  manufacturingYear: z.number().int().min(1900).max(2030),
  registrationYear: z.number().int().min(1900).max(2030).optional(),
  vin: z.string().optional(),
  engineNumber: z.string().optional(),
  plateNumber: z.string().optional(),
  color: z.string().min(1),
  countryOfOrigin: z.string().min(1),
  fuelType: z.string().optional(),
  engineSize: z.number().positive().optional(),
  horsepower: z.number().positive().optional(),
  transmission: z.string().optional(),
  drivetrain: z.string().optional(),
  cylinders: z.number().int().positive().optional(),
  seatingCapacity: z.number().int().positive().optional(),
  doors: z.number().int().positive().optional(),
  mileage: z.number().min(0).optional(),
  fuelConsumption: z.string().optional(),
  fuelTankCapacity: z.number().positive().optional(),
  groundClearance: z.number().positive().optional(),
  weight: z.number().positive().optional(),
  tireSize: z.string().optional(),
  condition: z.string().min(1),
  accidentFree: z.boolean().optional(),
  accidentHistory: z.string().optional(),
  serviceHistoryAvailable: z.boolean().optional(),
  ownershipCount: z.number().int().min(0).optional(),
  imported: z.boolean().optional(),
  locallyAssembled: z.boolean().optional(),
  safetyFeatures: z.array(z.string()).optional(),
  interiorFeatures: z.array(z.string()).optional(),
  exteriorFeatures: z.array(z.string()).optional(),
  dailyRate: z.number().positive().optional(),
  weeklyRate: z.number().positive().optional(),
  monthlyRate: z.number().positive().optional(),
  securityDeposit: z.number().positive().optional(),
  minRentalDays: z.number().int().positive().optional(),
  maxRentalDays: z.number().int().positive().optional(),
  driverIncluded: z.boolean().optional(),
  selfDrive: z.boolean().optional(),
  fuelPolicy: z.string().optional(),
  mileageLimit: z.number().int().optional(),
  extraKmCharge: z.number().positive().optional(),
  deliveryAvailable: z.boolean().optional(),
  airportPickup: z.boolean().optional(),
  availableLocations: z.array(z.string()).optional(),
  availableDates: z.string().optional(),
  driverAgeRequirement: z.number().int().optional(),
  minDrivingExperience: z.number().int().optional(),
  drivingLicenseRequired: z.string().optional(),
  passportRequired: z.boolean().optional(),
  smokingAllowed: z.boolean().optional(),
  petsAllowed: z.boolean().optional(),
  offroadAllowed: z.boolean().optional(),
  crossborderAllowed: z.boolean().optional(),
  insuranceIncluded: z.boolean().optional(),
  damageLiability: z.string().optional(),
  sellingPrice: z.number().positive().optional(),
  negotiable: z.boolean().optional(),
  financingAvailable: z.boolean().optional(),
  exchangeAccepted: z.boolean().optional(),
  bankLoanAccepted: z.boolean().optional(),
  regionRegistration: z.string().optional(),
  ownershipCertificate: z.boolean().optional(),
  roadFundPaid: z.boolean().optional(),
  insuranceValid: z.boolean().optional(),
  inspectionCertificate: z.boolean().optional(),
  customsClearance: z.boolean().optional(),
  dutyPaid: z.boolean().optional(),
  plateType: z.string().optional(),
  region: z.string().min(1),
  city: z.string().min(1),
  subCity: z.string().optional(),
  woreda: z.string().optional(),
  latitude: z.number().optional(),
  longitude: z.number().optional(),
  pickupAddress: z.string().optional(),
  description: z.string().optional(),
  images: z.array(z.string()).optional(),
  videoUrl: z.string().optional(),
  price: z.number().positive(),
  priceType: z.string(),
  features: z.array(z.string()).optional(),
  featured: z.boolean().optional(),
})
