import { connectDB } from "./config/database.js";
import { UserModel, PropertyModel, VehicleModel } from "./models/index.js";
import { hashPassword } from "./utils/password.js";

const SEED_PASSWORD = "SecurePass@123";

const img = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;

const USERS = [
  {
    email: "falmitesfaye@gmail.com",
    username: "Falmite Sefaye",
    phone: "+251911000001",
    role: "admin" as const,
    roles: ["admin"],
    isRootAdmin: true,
  },
  {
    email: "gammeforchange@gmail.com",
    username: "Gamme Forchange",
    phone: "+251911000002",
    role: "agent" as const,
    roles: ["agent"],
    isRootAdmin: false,
  },
  {
    email: "shalama@gmail.com",
    username: "Shalama",
    phone: "+251911000003",
    role: "user" as const,
    roles: ["user"],
    isRootAdmin: false,
  },
];

const PROPERTIES = [
  {
    title: "Modern 3-Bedroom Family Home in Bole Bulbula",
    type: "House",
    listingType: "For Sale" as const,
    price: 18500000,
    priceType: "Total",
    region: "Addis Ababa",
    city: "Addis Ababa",
    subCity: "Bole",
    woreda: "03",
    area: 320,
    bedrooms: 3,
    bathrooms: 3,
    condition: "New",
    legalizedYear: 2021,
    description:
      "A stunning modern home located in the quiet Bole Bulbula area. Fully finished with premium finishing, ample parking for three cars, a beautiful backyard garden, and close proximity to Bole Airport, schools and shopping centers.",
    features: ["WiFi", "Parking", "Backyard", "Water Tank", "Generator Ready", "Furnished Kitchen"],
    images: [img("photo-1580587771525-78b9dba3b914"), img("photo-1600566753190-17f0baa2a6c3"), img("photo-1600607687939-ce8a6c25118c")],
    videoUrl: "",
    featured: true,
    posterType: "Owner",
    ownerType: "Private",
    displayPhone: "+251911000002",
    status: "Approved" as const,
    latitude: 8.9876,
    longitude: 38.7896,
  },
  {
    title: "Luxury 4-Bedroom Villa with Garden in CMC",
    type: "Villa",
    listingType: "For Sale" as const,
    price: 28500000,
    priceType: "Total",
    region: "Addis Ababa",
    city: "Addis Ababa",
    subCity: "Yeka",
    woreda: "08",
    area: 520,
    bedrooms: 4,
    bathrooms: 4,
    condition: "New",
    legalizedYear: 2022,
    description:
      "Exceptional villa in CMC featuring four en-suite bedrooms, a spacious living area with high ceilings, modern kitchen, landscaped garden and a private compound with security. Perfect for families looking for comfort and privacy.",
    features: ["WiFi", "Parking", "Backyard", "Security", "Water Tank", "Generator Ready"],
    images: [img("photo-1600596542815-ffad4c1539a9"), img("photo-1512917774080-9991f1c4c750"), img("photo-1600566753086-00f18fb6b3ea")],
    featured: true,
    posterType: "Agent",
    ownerType: "Private",
    displayPhone: "+251911000002",
    status: "Approved" as const,
    latitude: 9.0215,
    longitude: 38.8007,
  },
  {
    title: "Spacious 2-Bedroom Apartment in Summit",
    type: "Apartment",
    listingType: "For Sale" as const,
    price: 9500000,
    priceType: "Total",
    region: "Addis Ababa",
    city: "Addis Ababa",
    subCity: "Bole",
    woreda: "13",
    area: 165,
    bedrooms: 2,
    bathrooms: 2,
    condition: "Used",
    legalizedYear: 2016,
    description:
      "Well-maintained apartment in Summit, Bole. Features two good-sized bedrooms, a bright living room, modern kitchen and balcony with a city view. Located in a compound with 24/7 security and elevator access.",
    features: ["WiFi", "Parking", "Elevator", "24/7 Security", "Water Tank"],
    images: [img("photo-1523217582562-09d0def993a6"), img("photo-1560448204-e02f11c3d0e2"), img("photo-1600210492486-724fe5c67fb0")],
    featured: false,
    posterType: "Agent",
    ownerType: "Private",
    displayPhone: "+251911000002",
    status: "Approved" as const,
    latitude: 8.9961,
    longitude: 38.8001,
  },
  {
    title: "Compact Studio Apartment for Rent in Gerji",
    type: "Studio",
    listingType: "For Rent" as const,
    price: 28000,
    priceType: "Monthly",
    region: "Addis Ababa",
    city: "Addis Ababa",
    subCity: "Bole",
    woreda: "11",
    area: 52,
    bedrooms: 0,
    bathrooms: 1,
    condition: "New",
    legalizedYear: 2020,
    description:
      "Furnished studio apartment in Gerji ideal for singles or young professionals. Includes a kitchenette, private bathroom and shared amenities in a modern compound with parking and security.",
    features: ["WiFi", "Furnished", "Parking", "Water Tank"],
    images: [img("photo-1522708323590-d24dbb6b0267"), img("photo-1502672260266-1c1ef2d93688"), img("photo-1493809842364-78817add7ffb")],
    featured: false,
    posterType: "Owner",
    ownerType: "Private",
    displayPhone: "+251911000002",
    status: "Approved" as const,
    latitude: 8.9943,
    longitude: 38.8052,
  },
  {
    title: "Prime Commercial Space on Africa Avenue",
    type: "Commercial",
    listingType: "For Sale" as const,
    price: 42000000,
    priceType: "Total",
    region: "Addis Ababa",
    city: "Addis Ababa",
    subCity: "Bole",
    woreda: "05",
    area: 410,
    bedrooms: 0,
    bathrooms: 2,
    condition: "New",
    legalizedYear: 2023,
    description:
      "High-traffic commercial space on Bole Road (Africa Avenue) suitable for showrooms, offices or banking. Glass façade, ample parking and excellent visibility on one of Addis Ababa's busiest streets.",
    features: ["Parking", "Elevator", "24/7 Security", "High Visibility"],
    images: [img("photo-1497366754035-f200968a6e72"), img("photo-1497366811353-6870744d04b2"), img("photo-1504384308090-c894fdcc538d")],
    featured: false,
    posterType: "Agent",
    ownerType: "Company",
    displayPhone: "+251911000002",
    status: "Approved" as const,
    latitude: 8.9981,
    longitude: 38.7811,
  },
  {
    title: "Beautiful Land Plot for Sale in Ayat",
    type: "Land",
    listingType: "For Sale" as const,
    price: 6500000,
    priceType: "Total",
    region: "Addis Ababa",
    city: "Addis Ababa",
    subCity: "Yeka",
    woreda: "12",
    area: 300,
    bedrooms: 0,
    bathrooms: 0,
    condition: "New",
    legalizedYear: 2024,
    description:
      "Clean and legalized land plot in Ayat for residential construction. The plot is flat with road access and is located in a developing neighborhood with water and electricity lines available nearby.",
    features: ["Fenced", "Road Access", "Legalized", "Water Access"],
    images: [img("photo-1500382017468-9049fed747ef"), img("photo-1518780664697-55e3ad937233")],
    featured: false,
    posterType: "Owner",
    ownerType: "Private",
    displayPhone: "+251911000002",
    status: "Approved" as const,
    latitude: 9.0301,
    longitude: 38.8087,
  },
];

const VEHICLES = [
  {
    title: "Toyota Land Cruiser V8 2015 - Excellent Condition",
    vehicleId: "DWL-VH-001",
    listingType: "For Sale" as const,
    vehicleCategory: "SUV",
    make: "Toyota",
    vehicleModel: "Land Cruiser 200",
    trimVersion: "V8 VXR",
    manufacturingYear: 2015,
    registrationYear: 2015,
    color: "White",
    countryOfOrigin: "UAE",
    fuelType: "Diesel",
    engineSize: 4.5,
    horsepower: 309,
    transmission: "Automatic",
    drivetrain: "4x4",
    seatingCapacity: 8,
    doors: 5,
    mileage: 124000,
    fuelConsumption: "10.9 L/100km",
    fuelTankCapacity: 138,
    condition: "Used",
    accidentFree: true,
    ownershipCount: 2,
    imported: true,
    price: 12400000,
    priceType: "Total",
    features: ["Reverse Camera", "Sunroof", "Leather Seats", "Bluetooth", "GPS", "Rear AC"],
    safetyFeatures: ["ABS", "Airbags", "EBD", "Cruise Control", "Parking Sensors"],
    interiorFeatures: ["Leather Seats", "Sunroof", "Premium Audio"],
    exteriorFeatures: ["Roof Rails", "Rear Spoiler", "Alloy Wheels"],
    region: "Addis Ababa",
    city: "Addis Ababa",
    subCity: "Bole",
    pickupAddress: "Bole, Addis Ababa",
    description:
      "Imported, duty-paid Land Cruiser V8 in pristine condition. Full service history, new tires, and a recent full inspection. Ideal for long-distance travel and off-road.",
    images: [img("photo-1606016159991-dfe4f2746ad5"), img("photo-1533473359331-0135ef1b58bf"), img("photo-1568605114967-8130f3a36994")],
    featured: true,
    status: "Approved" as const,
    views: 0,
    favorites: 0,
  },
  {
    title: "Toyota Vitz 2018 - Fuel Efficient City Car",
    vehicleId: "DWL-VH-002",
    listingType: "For Sale" as const,
    vehicleCategory: "Sedan",
    make: "Toyota",
    vehicleModel: "Vitz",
    trimVersion: "1.3 F",
    manufacturingYear: 2018,
    registrationYear: 2018,
    color: "Silver",
    countryOfOrigin: "Japan",
    fuelType: "Petrol",
    engineSize: 1.3,
    horsepower: 99,
    transmission: "Automatic",
    drivetrain: "2WD",
    seatingCapacity: 5,
    doors: 5,
    mileage: 86000,
    fuelConsumption: "5.2 L/100km",
    fuelTankCapacity: 42,
    condition: "Used",
    accidentFree: true,
    ownershipCount: 1,
    imported: true,
    price: 2750000,
    priceType: "Total",
    features: ["Power Steering", "AC", "Central Locking", "ABS", "Airbag"],
    safetyFeatures: ["ABS", "Airbags", "ISOFIX"],
    interiorFeatures: ["AC", "Power Windows"],
    exteriorFeatures: ["Alloy Wheels", "Sunroof"],
    region: "Addis Ababa",
    city: "Addis Ababa",
    subCity: "Nifas Silk-Lafto",
    pickupAddress: "Kality, Addis Ababa",
    description:
      "Well-kept Toyota Vitz with a clean interior and excellent fuel economy. Perfect first car for city driving. Genuine mileage and ready for immediate transfer.",
    images: [img("photo-1542362567-b07e54358753"), img("photo-1503376780353-7e6692767b70")],
    featured: true,
    status: "Approved" as const,
    views: 0,
    favorites: 0,
  },
  {
    title: "Toyota Corolla 2019 - Low Mileage",
    vehicleId: "DWL-VH-003",
    listingType: "For Sale" as const,
    vehicleCategory: "Sedan",
    make: "Toyota",
    vehicleModel: "Corolla",
    trimVersion: "SE",
    manufacturingYear: 2019,
    registrationYear: 2019,
    color: "Black",
    countryOfOrigin: "USA",
    fuelType: "Petrol",
    engineSize: 1.8,
    horsepower: 139,
    transmission: "Automatic",
    drivetrain: "2WD",
    seatingCapacity: 5,
    doors: 4,
    mileage: 58000,
    fuelConsumption: "6.6 L/100km",
    fuelTankCapacity: 50,
    condition: "Used",
    accidentFree: true,
    ownershipCount: 1,
    imported: true,
    price: 4150000,
    priceType: "Total",
    features: ["Touchscreen", "Reverse Camera", "Cruise Control", "Bluetooth"],
    safetyFeatures: ["ABS", "Airbags", "EBD", "Lane Assist"],
    interiorFeatures: ["Touchscreen", "Leather Steering"],
    exteriorFeatures: ["Alloy Wheels"],
    region: "Addis Ababa",
    city: "Addis Ababa",
    subCity: "Bole",
    pickupAddress: "Bole Medhanialem, Addis Ababa",
    description:
      "Low-mileage, accident-free Corolla with a full service history at the dealership. Comfortable, reliable, and efficient — an ideal family sedan.",
    images: [img("photo-1590362891991-f776e747a588"), img("photo-1550355291-bbee04a92027")],
    featured: false,
    status: "Approved" as const,
    views: 0,
    favorites: 0,
  },
  {
    title: "Suzuki Alto 2020 - Cheap to Run",
    vehicleId: "DWL-VH-004",
    listingType: "For Sale" as const,
    vehicleCategory: "Sedan",
    make: "Suzuki",
    vehicleModel: "Alto",
    trimVersion: "VXL",
    manufacturingYear: 2020,
    registrationYear: 2020,
    color: "Red",
    countryOfOrigin: "Japan",
    fuelType: "Petrol",
    engineSize: 0.8,
    horsepower: 47,
    transmission: "Manual",
    drivetrain: "2WD",
    seatingCapacity: 4,
    doors: 5,
    mileage: 41000,
    fuelConsumption: "3.9 L/100km",
    fuelTankCapacity: 32,
    condition: "Used",
    accidentFree: true,
    ownershipCount: 1,
    imported: true,
    price: 2150000,
    priceType: "Total",
    features: ["AC", "Power Steering", "Central Locking"],
    safetyFeatures: ["Airbags", "ABS"],
    interiorFeatures: ["AC"],
    exteriorFeatures: ["Alloy Wheels"],
    region: "Addis Ababa",
    city: "Addis Ababa",
    subCity: "Arada",
    pickupAddress: "Megenagna, Addis Ababa",
    description:
      "Very economical Suzuki Alto in great running condition. Excellent fuel economy, cheap maintenance, and perfect for navigating Addis traffic.",
    images: [img("photo-1549317661-bd32c8ce0db2"), img("photo-1580273916550-e323be2ae537")],
    featured: false,
    status: "Approved" as const,
    views: 0,
    favorites: 0,
  },
  {
    title: "Hyundai Tucson 2021 - Family SUV",
    vehicleId: "DWL-VH-005",
    listingType: "For Sale" as const,
    vehicleCategory: "SUV",
    make: "Hyundai",
    vehicleModel: "Tucson",
    trimVersion: "Limited",
    manufacturingYear: 2021,
    registrationYear: 2021,
    color: "White",
    countryOfOrigin: "Korea",
    fuelType: "Petrol",
    engineSize: 2.0,
    horsepower: 156,
    transmission: "Automatic",
    drivetrain: "AWD",
    seatingCapacity: 5,
    doors: 5,
    mileage: 52000,
    fuelConsumption: "8.2 L/100km",
    fuelTankCapacity: 62,
    condition: "Used",
    accidentFree: true,
    ownershipCount: 1,
    imported: true,
    price: 6850000,
    priceType: "Total",
    features: ["Touchscreen", "Reverse Camera", "Sunroof", "Cruise Control", "Apple CarPlay"],
    safetyFeatures: ["ABS", "Airbags", "EBD", "Lane Keep Assist", "Blind Spot"],
    interiorFeatures: ["Leather Seats", "Sunroof", "Touchscreen"],
    exteriorFeatures: ["Alloy Wheels", "Roof Rails"],
    region: "Addis Ababa",
    city: "Addis Ababa",
    subCity: "Yeka",
    pickupAddress: "CMC, Addis Ababa",
    description:
      "Modern Tucson with low mileage and all the safety features. Spacious, comfortable and well-maintained — great for families.",
    images: [img("photo-1583121274602-3e2820c69888"), img("photo-1552519507-da3b142c6e3d")],
    featured: false,
    status: "Approved" as const,
    views: 0,
    favorites: 0,
  },
  {
    title: "Toyota RAV4 2017 - Reliable Compact SUV",
    vehicleId: "DWL-VH-006",
    listingType: "For Sale" as const,
    vehicleCategory: "SUV",
    make: "Toyota",
    vehicleModel: "RAV4",
    trimVersion: "XLE",
    manufacturingYear: 2017,
    registrationYear: 2017,
    color: "Grey",
    countryOfOrigin: "Japan",
    fuelType: "Petrol",
    engineSize: 2.5,
    horsepower: 176,
    transmission: "Automatic",
    drivetrain: "AWD",
    seatingCapacity: 5,
    doors: 5,
    mileage: 98000,
    fuelConsumption: "8.7 L/100km",
    fuelTankCapacity: 60,
    condition: "Used",
    accidentFree: false,
    accidentHistory: "Minor front bumper repair in 2019, fully replaced with OEM parts.",
    ownershipCount: 2,
    imported: true,
    price: 5450000,
    priceType: "Total",
    features: ["Reverse Camera", "Cruise Control", "Bluetooth", "Roof Rails"],
    safetyFeatures: ["ABS", "Airbags", "EBD"],
    interiorFeatures: ["Touchscreen", "AC"],
    exteriorFeatures: ["Alloy Wheels"],
    region: "Addis Ababa",
    city: "Addis Ababa",
    subCity: "Kolfe Keranio",
    pickupAddress: "Ambo Road, Addis Ababa",
    description:
      "Dependable RAV4 with a minor recorded history. Recent full service, new brakes and tires. A smart buy for city and country driving.",
    images: [img("photo-1519641471654-76ce0107ad1b"), img("photo-1533473359331-0135ef1b58bf")],
    featured: false,
    status: "Approved" as const,
    views: 0,
    favorites: 0,
  },
];

async function upsertUser(data: (typeof USERS)[number]) {
  const password = await hashPassword(SEED_PASSWORD);
  const [user] = await UserModel.findOrCreate({
    where: { email: data.email },
    defaults: {
      username: data.username,
      email: data.email,
      phone: data.phone,
      password,
      role: data.role,
      roles: data.roles,
      status: "Approved",
      isRootAdmin: data.isRootAdmin,
      emailVerified: true,
      onboardingComplete: true,
    } as any,
  });
  await user.update({
    username: data.username,
    phone: data.phone,
    password,
    role: data.role,
    roles: data.roles,
    status: "Approved",
    isRootAdmin: data.isRootAdmin,
    emailVerified: true,
    onboardingComplete: true,
  } as any);
  return user;
}

async function upsertProperty(data: (typeof PROPERTIES)[number], agentId: string, agentName: string) {
  const existing = await PropertyModel.findOne({ where: { title: data.title, agentId } });
  if (existing) {
    await existing.update({ ...data, agentId, agentName } as any);
    return existing;
  }
  return PropertyModel.create({ ...data, agentId, agentName } as any);
}

async function upsertVehicle(data: (typeof VEHICLES)[number], agentId: string, agentName: string) {
  const existing = await VehicleModel.findOne({ where: { vehicleId: data.vehicleId } });
  if (existing) {
    await existing.update({ ...data, agentId, agentName } as any);
    return existing;
  }
  return VehicleModel.create({ ...data, agentId, agentName } as any);
}

async function seed() {
  const db = await connectDB();
  if (!db) {
    console.error("❌ Could not connect to the database. Aborting seed.");
    process.exit(1);
  }

  console.log("🌱 Seeding DawoLife database...");

  const admin = await upsertUser(USERS[0]);
  const agent = await upsertUser(USERS[1]);
  const buyer = await upsertUser(USERS[2]);
  console.log(`✅ Users ready (admin=${admin.getDataValue("email")}, agent=${agent.getDataValue("email")}, user=${buyer.getDataValue("email")})`);

  const agentId = agent.getDataValue("id") as string;

  for (const p of PROPERTIES) {
    await upsertProperty(p, agentId, agent.getDataValue("username"));
  }
  console.log(`✅ ${PROPERTIES.length} properties seeded/updated (status=Approved)`);

  for (const v of VEHICLES) {
    await upsertVehicle(v, agentId, agent.getDataValue("username"));
  }
  console.log(`✅ ${VEHICLES.length} vehicles seeded/updated (status=Approved)`);

  await db.close();
  console.log("🎉 Seed complete. All accounts share password: " + SEED_PASSWORD);
  process.exit(0);
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
